name: CI/CD Pipeline
on:
  workflow_dispatch:
jobs:
  build-likes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: kerstenremco
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tagging for likes
        id: meta-likes
        uses: docker/metadata-action@v5
        with:
          images: kerstenremco/remcokerstennl-blog-backend-likes
          tags: type=sha
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 12

      - name: Build likes image
        uses: docker/build-push-action@v6
        with:
          context: ./likes
          file: ./likes/Dockerfile
          push: true
          tags: ${{ steps.meta-likes.outputs.tags }}

      - name: Docker tagging for contact
        id: meta-contact
        uses: docker/metadata-action@v5
        with:
          images: kerstenremco/remcokerstennl-blog-backend-contact
          tags: type=sha
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 12

      - name: Build contact image
        uses: docker/build-push-action@v6
        with:
          context: ./contact
          file: ./contact/Dockerfile
          push: true
          tags: ${{ steps.meta-contact.outputs.tags }}
      - name: Checkout cd repo
        uses: actions/checkout@v4
        with:
          repository: kerstenremco/remcokersten-blog-infra
          path: infrarepo
          token: ${{ secrets.GH_TOKEN }}
      - name: Commit and push changes (if any)
        shell: bash
        env:
          CI_COMMIT_MESSAGE: Update Argo CD
          CI_COMMIT_AUTHOR: remcokerstennl-blog-github-bot
          CI_COMMIT_EMAIL: ghbot@remcokersten.nl
        run: |
          cd infrarepo
          sed -i "s#kerstenremco/remcokerstennl-blog-backend-likes:[^[:space:]]*#${{ steps.meta-likes.outputs.tags }}#g" likes/deployment.yml
          sed -i "s#kerstenremco/remcokerstennl-blog-backend-contact:[^[:space:]]*#${{ steps.meta-contact.outputs.tags }}#g" contact/deployment.yml
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          # Changes
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
